version: "3.8"
services:
  arangodb:
    image: arangodb
    ports:
      - "8529:8529"
    networks:
      - botify-network

  botify_server:
    build: .
    depends_on:
      - arangodb
    networks:
      - botify-network
    ports:
      - "8081:8081"
      - "8080:8080"

networks:
  botify-network:
    driver: bridge
